// BOOL
#define FALSE 0
#define TRUE 1
// Window data
#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600
// Card data
#define DECK_SIZE 52
#define CARD_WIDTH 48
#define CARD_HEIGHT 64
// Board positions
#define TABLEAU_COLUMS 7
#define TABLEAU_X 74
#define TABLEAU_X_INCREMENT 82
#define TABLEAU_Y 204
#define TABLEAU_Y_INCREMENT 34
#define FOUNDATION_COLUMNS 4
#define FOUNDATION_X 383
#define FOUNDATION_X_INCREMENT 82
#define STOCK_X 74
#define WASTE_X 172
#define TOP_Y 44
